version: '3.8'

services:
  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    command:  bash -c "alembic upgrade head && uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

  test_db:
    image: postgres:latest
    container_name: test_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_TEST_USER}
      POSTGRES_PASSWORD: ${DB_TEST_PASSWORD}
      POSTGRES_DB: ${DB_TEST_NAME}
    ports:
      - '5434:5432'

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - '1715:80'
    depends_on:
      - backend

  test:
    container_name: test
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
    command: pytest tests
    depends_on:
      - postgres
      - test_db